<?php

namespace ContainerR6Czx1a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hcYskd1.App\Entity\Don' shared service.
     *
     * @return \App\Entity\Don
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hcYskd1": it references class "App\\Entity\\Don" but no such service exists.');
    }
}
