<?php

namespace ContainerTUJrjcQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6Rd1IoKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Rd1IoK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Rd1IoK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'association' => ['privates', '.errored..service_locator.6Rd1IoK.App\\Entity\\Association', NULL, 'Cannot autowire service ".service_locator.6Rd1IoK": it references class "App\\Entity\\Association" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'association' => 'App\\Entity\\Association',
            'entityManager' => '?',
        ]);
    }
}
