<?php

namespace ContainerRI4MxdC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5NKX_KpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5NKX.Kp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5NKX.Kp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'association' => ['privates', '.errored..service_locator.5NKX.Kp.App\\Entity\\Association', NULL, 'Cannot autowire service ".service_locator.5NKX.Kp": it references class "App\\Entity\\Association" but no such service exists.'],
        ], [
            'association' => 'App\\Entity\\Association',
        ]);
    }
}
