<?php

namespace ContainerRI4MxdC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssociation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6Rd1IoK.App\Entity\Association' shared service.
     *
     * @return \App\Entity\Association
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6Rd1IoK": it references class "App\\Entity\\Association" but no such service exists.');
    }
}
