<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCf5ogGP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCf5ogGP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCf5ogGP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCf5ogGP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCf5ogGP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cf5ogGP',
    'container.build_id' => 'e86bf085',
    'container.build_time' => 1681441234,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCf5ogGP');
