<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTUJrjcQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTUJrjcQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTUJrjcQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTUJrjcQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTUJrjcQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'TUJrjcQ',
    'container.build_id' => 'fe002b07',
    'container.build_time' => 1683124976,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTUJrjcQ');
