<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR6Czx1a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR6Czx1a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR6Czx1a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR6Czx1a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR6Czx1a\App_KernelDevDebugContainer([
    'container.build_hash' => 'R6Czx1a',
    'container.build_id' => 'dfc69f9b',
    'container.build_time' => 1682621475,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR6Czx1a');
